language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "lts/*"
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
